### PR TITLE
use vscode builtin icons instead of png icon for tree 

### PR DESCRIPTION
**Pull request by ctf0**
use vscode builtin icons instead of imgs for activity bar view

### CODE REVIEW

**Comment by zabel-xyz** [comment]
No in stable vscode version yet, (work in inside version only)

**Comment by ctf0** [comment]
oh i missed that

**Comment by ctf0** [comment]
https://code.visualstudio.com/updates/v1_42#_codicons-for-reuse

**Comment by zabel-xyz** [comment]
Version 1.8.0

**Pull request closed without merging**
